### ISSUE TITLE
ENOENT error

### ISSUE THREAD

**Issue by Shuunen** [sindresorhus/one-thing#1]
Hi there,

Here is the output from my git bash on Windows 10 x64 Node 14.17.3 : 

```text
$ npm install --global one-thing
C:\Users\Me\Apps\NodeJs14\one-thing -> C:\Users\Me\Apps\NodeJs14\node_modules\one-thing\cli.js
+ one-thing@1.1.0
added 61 packages from 46 contributors in 18.173s

$ one-thing 'Meet John Doe for a coffee'
Error: spawn open ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

Any idea ?

It says in the readme `Require node 12`, is it only node 12 or node 12 minimum ?

Regards

**Comment by sindresorhus** [comment]
> Set the text for the One Thing app

You need the One Thing app.

**Comment by Shuunen** [comment]
Lol ok seems pretty obvious now, at first sight it seems to me that it was a cli and an electron app all bundled in this npm package

Anyway sorry for this silly issue, thanks Sindre for all the contributions you're making in the OSS world <3
