### ISSUE TITLE
Error: Command failed: open --background one-thing:?text=Prepare%20for%20important%20meeting

### ISSUE THREAD

**Issue by tomatobybike** [sindresorhus/one-thing#2]
one-thing 'Prepare for important meeting'

Error: Command failed: open --background one-thing:?text=Prepare%20for%20important%20meeting
No application knows how to open URL one-thing:?text=Prepare%20for%20important%20meeting (Error Domain=NSOSStatusErrorDomain Code=-10814 "kLSApplicationNotFoundErr: E.g. no application claims the file" UserInfo={_LSLine=1489, _LSFunction=runEvaluator}).

    at ChildProcess.exithandler (node:child_process:397:12)

=========
nodejs v16.13.2
macbook

**Comment by sindresorhus** [comment]
Do you have the "One Thing" app installed?

**Comment by tomatobybike** [comment]
> Do you have the "One Thing" app installed?

NO.

I just use 

`
yarn global add  one-thing
one-thing 'Prepare for important meeting'
`

I'll install the app, and try again

**Comment by tomatobybike** [comment]
> Do you have the "One Thing" app installed?

after install app， i do it success .
thanks
