### ISSUE TITLE
[OFFTOPIC] Why isn't the app itself open sourced?

### ISSUE THREAD

**Issue by BlueFalconHD** [sindresorhus/one-thing#4]
I would love it so much to be able to modify this a little to work perfectly for my workflow.

**Comment by sindresorhus** [comment]
I open source many of my apps. However, open sourcing an app comes with some downsides and very few upsides. The downsides are that I cannot use my internal framework that makes it much faster to make apps, some may upload clones to the App Store (happened in the past), if I get any contributions at all, they're usually very low-quality.

So in short, I love open sourcing tools and the building blocks for my apps, but open sourcing an app is often more work than it's worth.

**Comment by sindresorhus** [comment]
I'm curious, how would you modify it?

**Comment by BlueFalconHD** [comment]
I think I would add a system for an icon, as the workaround (setting the prefix to an emoji) doesn't really work for me. Also, I would add a scheduled system, maybe integrating with calendar or reminders, where it would show one at a time. 

P.S. This app inspired me to change my workflow for schoolwork too, as it worked so well.

**Comment by BlueFalconHD** [comment]
@sindresorhus another thing I would add is multiple instances of one thing per desktop. So on my desktop I use for git, there would be a separate instance for personal things.

**Comment by sindresorhus** [comment]
> I think I would add a system for an icon, as the workaround (setting the prefix to an emoji) doesn't really work for me.

Better icon support is something I'm considering. How would you want it to work?

> Also, I would add a scheduled system, maybe integrating with calendar or reminders, where it would show one at a time.

This can already be done using the shortcuts integration: https://sindresorhus.com/one-thing#how-can-i-show-the-next-task-in-the-today-list-in-things-in-one-thing

> another thing I would add is multiple instances of one thing per desktop. So on my desktop I use for git, there would be a separate instance for personal things.

I made something for you: https://sindresorhus.com/one-thing#one-thing2

**Comment by BlueFalconHD** [comment]
Thank you so much! I would like the icon to just be an SF Symbol with color that can be different from text. Just like entering the SF Symbol code.

**Comment by BlueFalconHD** [comment]
Also, can you call the second version 2 thing? :shipit:

**Comment by BlueFalconHD** [comment]
@sindresorhus I forgot 2 things. ICloud/whatever other service sync and apple watch app (standalone)

**Comment by sindresorhus** [comment]
Both of those are on my todo list.

**Comment by vivindeena** [comment]
hey @sindresorhus  is there a way to write text to the One Thing App using CLI tool like bash or something

**Comment by sindresorhus** [comment]
https://sindresorhus.com/one-thing#custom-url-scheme
