### ISSUE TITLE
`open --background` still causes frontmost app to lose focus

### ISSUE THREAD

**Issue by luckman212** [sindresorhus/one-thing#6]
Thanks for One Thing! 🌈 🦄

Small issue, but when using the URI scheme to set a message

```
open --background "one-thing:?text=Foo%20Bar"
```
The frontmost app will lose focus. I have some scripts that set messages using this method and it causes minor frustration when I am e.g. typing in Sublime Text and I have to reach for the mouse to bring it back to the front.

~~The Node CLI does not have this problem~~, so I switched to that for now, but the URI scheme is "easier" 

**edit**: actually, the node cli _does_ have the same gotcha.

**Comment by sindresorhus** [comment]
This only happens when One Thing is not already running, correct?

**Comment by luckman212** [comment]
Correct, sorry I left out that detail.

**Comment by sindresorhus** [comment]
Fixed in 1.11.2
